name: Update Changelog

on:
  release:
    types: [released]

permissions: {}

jobs:
  update:
    permissions:
      contents: write
    uses: doppar/flarion/.github/workflows/update-changelog.yml@main